fixed build error because of -Wmissing-braces warnings:
palette.c:29:2: error: missing braces around initializer [-Werror=missing-braces]
  {0x1, 0x59, 0x75, 0x7f, 0x8e, 0x9a, 0xa5, 0xab, },
  ^